### GET ALL USERS
GET http://localhost:3000/users

### GET USER BY ID 
GET http://localhost:3000/users/7f57f6b3-3910-4993-bb94-931d0851eec8/

### CREATE USER 
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "pilondg",
  "email": "pilon.dev@gmail.com",
  "password": "1234"
}

### UPDATE USER
PUT http://localhost:3000/users/16
Content-Type: application/json

{
  "email": "Taliwas@gmail.com",
  "username": "Taliwas"
}

### DELETE USER 
DELETE http://localhost:3000/users/19

### LOGIN USER
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "pilondg",
  "email": "pilon.dev@gmail.com",
  "password": "1234"
}

