### GET ALL USERS
GET http://localhost:3000/users

### GET USER BY ID 
GET http://localhost:3000/users/2

### CREATE USER 
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "CarlosMartinez",
  "email": "carlosM@gmail.com",
  "password": "1234"
}

### UPDATE USER
PUT http://localhost:3000/users/16
Content-Type: application/json

{
  "email": "Taliwas@gmail.com",
  "username": "Taliwas"
}

### DELETE USER 
DELETE http://localhost:3000/users/19

